[package]
name = "detect-bias-welch"
version = "0.1.0"
authors = ["beltegeuse <adrien.gruson@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "*"

[dev-dependencies]
clap = "*"
image = "*"
byteorder = "*"
anyhow = "1.0"